# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Validacao(object):
    def setupUi(self, Validacao):
        Validacao.setObjectName("Validacao")
        Validacao.resize(800, 600)
        Validacao.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(Validacao)
        self.centralwidget.setObjectName("centralwidget")
        self.dropdown = QtWidgets.QComboBox(self.centralwidget)
        self.dropdown.setGeometry(QtCore.QRect(350, 40, 121, 31))
        font = QtGui.QFont()
        font.setFamily("HoloLens MDL2 Assets")
        font.setPointSize(13)
        self.dropdown.setFont(font)
        self.dropdown.setStyleSheet("color: rgb(106, 106, 106);\n"
"border-color: rgb(106, 106, 106);")
        self.dropdown.setObjectName("dropdown")
        self.dropdown.addItem("")
        self.dropdown.addItem("")
        self.dropdown.addItem("")
        self.dropdown.addItem("")
        self.dropdown.addItem("")
        self.dropdown.addItem("")
        self.label_type = QtWidgets.QLabel(self.centralwidget)
        self.label_type.setGeometry(QtCore.QRect(50, 30, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_type.setFont(font)
        self.label_type.setStyleSheet("")
        self.label_type.setObjectName("label_type")
        self.label_file = QtWidgets.QLabel(self.centralwidget)
        self.label_file.setGeometry(QtCore.QRect(50, 260, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_file.setFont(font)
        self.label_file.setObjectName("label_file")
        self.upload = QtWidgets.QPushButton(self.centralwidget)
        self.upload.setGeometry(QtCore.QRect(450, 260, 171, 51))
        font = QtGui.QFont()
        font.setFamily("HoloLens MDL2 Assets")
        font.setPointSize(21)
        self.upload.setFont(font)
        self.upload.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(0, 123, 255);\n"
"color: rgb(255, 255, 255);")
        self.upload.setObjectName("upload")
        self.download = QtWidgets.QPushButton(self.centralwidget)
        self.download.setGeometry(QtCore.QRect(310, 470, 171, 51))
        font = QtGui.QFont()
        font.setFamily("HoloLens MDL2 Assets")
        font.setPointSize(21)
        self.download.setFont(font)
        self.download.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(0, 123, 255);\n"
"color: rgb(255, 255, 255);")
        self.download.setObjectName("download")
        self.label_loading = QtWidgets.QLabel(self.centralwidget)
        self.label_loading.setGeometry(QtCore.QRect(120, 400, 561, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_loading.setFont(font)
        self.label_loading.setObjectName("label_loading")
        self.label_cod = QtWidgets.QLabel(self.centralwidget)
        self.label_cod.setGeometry(QtCore.QRect(50, 140, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_cod.setFont(font)
        self.label_cod.setStyleSheet("")
        self.label_cod.setObjectName("label_cod")
        self.num_cod = QtWidgets.QLineEdit(self.centralwidget)
        self.num_cod.setGeometry(QtCore.QRect(450, 120, 171, 71))
        font = QtGui.QFont()
        font.setFamily("HoloLens MDL2 Assets")
        font.setPointSize(34)
        self.num_cod.setFont(font)
        self.num_cod.setStyleSheet("border-width: 1px;\n"
"border-style: solid;\n"
"border-radius: 5px;\n"
"border-color: rgb(0, 123, 255);")
        self.num_cod.setText("")
        self.num_cod.setAlignment(QtCore.Qt.AlignCenter)
        self.num_cod.setObjectName("num_cod")
        Validacao.setCentralWidget(self.centralwidget)

        self.retranslateUi(Validacao)
        QtCore.QMetaObject.connectSlotsByName(Validacao)

    def retranslateUi(self, Validacao):
        _translate = QtCore.QCoreApplication.translate
        Validacao.setWindowTitle(_translate("Validacao", "Validador"))
        self.dropdown.setItemText(0, _translate("Validacao", "Selecione ..."))
        self.dropdown.setItemText(1, _translate("Validacao", "BN"))
        self.dropdown.setItemText(2, _translate("Validacao", "BO"))
        self.dropdown.setItemText(3, _translate("Validacao", "BP"))
        self.dropdown.setItemText(4, _translate("Validacao", "RB"))
        self.dropdown.setItemText(5, _translate("Validacao", "RP"))
        self.label_type.setText(_translate("Validacao", "Tipo de arquivo"))
        self.label_file.setText(_translate("Validacao", "Arquivo a ser validado"))
        self.upload.setText(_translate("Validacao", "Pesquisar"))
        self.download.setText(_translate("Validacao", "Download"))
        self.label_loading.setText(_translate("Validacao", "Aguarde o carregamento do seu arquivo ..."))
        self.label_cod.setText(_translate("Validacao", "Código do Município"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Validacao = QtWidgets.QMainWindow()
    ui = Ui_Validacao()
    ui.setupUi(Validacao)
    Validacao.show()
    sys.exit(app.exec_())
